#!/bin/sh

# Installing basic text editors
#apt-get update
#apt-get --yes install emacs nano neovim vim

# Installing atom
#wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | apt-get-key add -
#echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt-get/sources.list.d/atom.list
#apt-get update
#apt-get --yes install atom

# Installing sublime-text
#wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-get-key add -
#echo "deb https://download.sublimetext.com/ apt-get/stable/" > /etc/apt-get/sources.list.d/sublime-text.list
#apt-get update
#apt-get --yes install sublime-text
