#!/bin/sh

# Installing libre office

#add-apt-get-repository ppa:libreoffice/ppa -y
#apt-get --yes update
#apt-get --yes install libreoffice
#apt-get --yes install hunspell-en-us hyphen-en-us mythes-en-us libreoffice-help-en-us
#apt-get --yes install hunspell-fr hyphen-fr mythes-fr libreoffice-help-fr
#apt-get --yes  install libreoffice-gtk3
#apt-get --yes install libreoffice-style*
