#! /bin/bash

tar --create --listed-incremental=backup.snap --verbose --file=backup.tar /etc /home /bin

#se crée dans /var/spool/cron/crontabs/root

PATH=/var/spool/cron/crontabs/root

echo "59 23 * * 1 tar -czvg backup.snap -f backup-\$(date +'%d_%m_%Y').tar /etc /home /bin" >> $PATH