#! /bin/bash

# assign classes to hosts based on their hostname

# do not use this if a menu will be presented
#[ "$flag_menu" ] && exit 0

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
        echo "FAIBASE DEBIAN DEMO FAISERVER STANDARD UTILS FRENCH" ;;
    employee*)
        echo "FAIBASE DEBIAN XORG XFCE LVM STANDARD UTILS EMPLOYEE FRENCH BACKUP";;
    zebihost*)
        echo "FAIBASE SYSADMIN DEBIAN XORG XFCE LVM STANDARD UTILS BACKUP";;
esac
