#! /bin/bash

# assign classes to hosts based on their hostname

# do not use this if a menu will be presented
#[ "$flag_menu" ] && exit 0

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
        echo "FAIBASE DEBIAN DEMO FAISERVER STANDARD UTILS" ;;
    client*)
        echo "FAIBASE DEBIAN UBUNTU FOCAL FOCAL64 XORG LVM STANDARD UTILS";;
    xfcehost*)
        echo "FAIBASE DEBIAN XORG LVM STANDARD UTILS";;
esac
